version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_DATABASE=explore_world
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  exploreworld:
    image: peteshonik/exploreworld:v1
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db